// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhQpACpzE5ExxRSQXliV6jtTEi5CNnauY',
    appId: '1:427298903807:web:9b42856e3eb4b7dc035eca',
    messagingSenderId: '427298903807',
    projectId: 'bookmanagement-23139',
    authDomain: 'bookmanagement-23139.firebaseapp.com',
    storageBucket: 'bookmanagement-23139.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC10Fk0eAF4KJBBR5KhsTclZ0uDlU7GSlM',
    appId: '1:427298903807:android:a52e2884897ad4f3035eca',
    messagingSenderId: '427298903807',
    projectId: 'bookmanagement-23139',
    storageBucket: 'bookmanagement-23139.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx8IsWbsWZb2siRSAOwlZXcHkT9yIoLhc',
    appId: '1:427298903807:ios:38f9db383f00ed94035eca',
    messagingSenderId: '427298903807',
    projectId: 'bookmanagement-23139',
    storageBucket: 'bookmanagement-23139.firebasestorage.app',
    iosBundleId: 'com.example.ex8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx8IsWbsWZb2siRSAOwlZXcHkT9yIoLhc',
    appId: '1:427298903807:ios:38f9db383f00ed94035eca',
    messagingSenderId: '427298903807',
    projectId: 'bookmanagement-23139',
    storageBucket: 'bookmanagement-23139.firebasestorage.app',
    iosBundleId: 'com.example.ex8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhQpACpzE5ExxRSQXliV6jtTEi5CNnauY',
    appId: '1:427298903807:web:0f87322555c3991b035eca',
    messagingSenderId: '427298903807',
    projectId: 'bookmanagement-23139',
    authDomain: 'bookmanagement-23139.firebaseapp.com',
    storageBucket: 'bookmanagement-23139.firebasestorage.app',
  );

}